<?php
/**
 * Language labels for database tables/fields belonging to extension "typoflash"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"pages.tx_typoflash_template" => "Flash page template",	
		"pages.tx_typoflash_conf" => "Flash page configuration",
		"pages.tx_typoflash_data" => "Flash page data",
		"tx_typoflash_template" => "Flash template",	
		"tx_typoflash_template.name" => "Name",	
		"tx_typoflash_template.width" => "Width (e.g. 750px or 100%)",	
		"tx_typoflash_template.height" => "Height  (e.g. 1000px or 100%)",	
		"tx_typoflash_template.version" => "Flash player version",
		"tx_typoflash_template.version.I.0" => "5",
		"tx_typoflash_template.version.I.1" => "6",
		"tx_typoflash_template.version.I.2" => "7",
		"tx_typoflash_template.version.I.3" => "8",
		"tx_typoflash_template.version.I.4" => "9",
		"tx_typoflash_template.version.I.5" => "10",
		"tx_typoflash_template.version.I.6" => "Lite 1.0",
		"tx_typoflash_template.version.I.7" => "Lite 1.1",
		"tx_typoflash_template.version.I.8" => "Lite 2.0",
		"tx_typoflash_template.version.I.9" => "Lite 2.1",
		"tx_typoflash_template.dynamic_fonts" => "Dynamic fonts",
		"tx_typoflash_template.dynamic_fonts.I.0" => "Arial",
		"tx_typoflash_template.dynamic_fonts.I.1" => "FFF Aquarius",
		"tx_typoflash_template.dynamic_fonts.I.2" => "Helvetica Neue",
		"tx_typoflash_template.dynamic_fonts.I.3" => "Verdana",
		"tx_typoflash_template.dynamic_fonts.I.4" => "Trebuchet MS",
		"tx_typoflash_template.dynamic_fonts.I.5" => "InfoText Regular",
		"tx_typoflash_template.dynamic_fonts.I.6" => "Palatino",
		"tx_typoflash_template.dynamic_fonts.I.7" => "Georgia",
		"tx_typoflash_template.dynamic_fonts.I.8" => "Caslon",
		"tx_typoflash_template.dynamic_fonts.I.9" => "Caslon Bold",
		"tx_typoflash_template.dynamic_fonts.I.10" => "Caslon Italic",
		"tx_typoflash_template.dynamic_fonts.I.11" => "PW Extended",
		"tx_typoflash_template.dynamic_fonts.I.12" => "Grotesque MT",
		"tx_typoflash_template.dynamic_fonts.I.13" => "Grotesque MT Light",
		"tx_typoflash_template.dynamic_fonts.I.14" => "Munica Regular",
		"tx_typoflash_template.dynamic_fonts.I.15" => "Myriad Pro",
		"tx_typoflash_template.fullscreen" => "Allow fullscreen mode",
		"tx_typoflash_template.asversion" => "ActionScript version",
		"tx_typoflash_template.asversion.I.0" => "AS1",
		"tx_typoflash_template.asversion.I.1" => "AS2",
		"tx_typoflash_template.asversion.I.2" => "AS3",
		"tx_typoflash_template.menu" => "Show menu",	
		"tx_typoflash_template.bgcolour" => "Background colour (e.g. #232323)",	
		"tx_typoflash_template.movieid" => "Movie id (for use with FlashVars etc)",	
		"tx_typoflash_template.historyframe" => "Enable browser history",	
		"tx_typoflash_template.file" => "Template SWF",	
		"tx_typoflash_template.css" => "CSS (included in HTML header)",	
		"tx_typoflash_template.title" => "Page title",	
		"tx_typoflash_template.metakeyword" => "Meta keywords (e.g. travel,rental)",	
		"tx_typoflash_template.metadesc" => "Meta description",	
		"tx_typoflash_template.searchengine" => "Search engine optimize (render text content in background)",	
		"tx_typoflash_template.redirectpage" => "Redirect page (on no flash)",	
		"tx_typoflash_template.conf" => "Configuration (use TypoFlash to edit, e.g. menu=444&start=home)",
		"tx_typoflash_template.language_file" => "Language file (xml)", 
		"tx_typoflash_component" => "Flash component",	
		"tx_typoflash_component.name" => "Name",	
		"tx_typoflash_component.prop_x" => "Flash property: _x",	
		"tx_typoflash_component.prop_y" => "Flash property: _y",	
		"tx_typoflash_component.prop_alpha" => "Flash property: _alpha",	
		"tx_typoflash_component.file" => "Component SWF",	
		"tx_typoflash_component.path" => "Frame/path to load component into (if not default)",	
		"tx_typoflash_component.target" => "Frame to load component into (if not default)",	
		"tx_typoflash_component.conf" => "Vars to send to component, e.g. edit=1&title=News",	
		"tx_typoflash_component.recordLimit" => "Max number of records to display",	
		"tx_typoflash_component.orderBy" => "Order records by (field must exist)",	
		"tx_typoflash_component.orderBy.I.1" => "Id",	
		"tx_typoflash_component.orderBy.I.2" => "Name",	
		"tx_typoflash_component.orderBy.I.3" => "Title",	
		"tx_typoflash_component.orderBy.I.4" => "Created date",
		"tx_typoflash_component.orderBy.I.5" => "Page id",
		"tx_typoflash_component.records_component" => "Specific records to load into component",	
		"tx_typoflash_component.records" => "Specific records",	
		"tx_typoflash_component.tables" => "Only select from these tables, e.g. fe_users,tt_news",	
		"tx_typoflash_component.content_records" => "Flash content records",	
		"tx_typoflash_component.storage" => "Load all tt_content records from this folder",	
		"tx_typoflash_component.initobj" => "Vars to send to component, e.g. edit=1&title=News",
		"tx_typoflash_component.seo" => "Search Engine Optimization",

		"tx_typoflash_component.seo_what_to_render" => "Select search engine content",

		"tx_typoflash_component.what_to_render.I.0" => "Content selected below",	
		"tx_typoflash_component.what_to_render.I.1" => "Same as flash",	
		"tx_typoflash_component.what_to_render.I.2" => "All content from this page",	
		"tx_typoflash_component.what_to_render.I.3" => "Same as no flash",	


		"tx_typoflash_component.non_flash" => "No Flash",
		"tx_typoflash_component.install_flash_link" => "Show link to Flash plugin",
		"tx_typoflash_component.what_to_render" => "Select content",
		"tx_typoflash_component.non_flash_what_to_render" => "Select non-flash content",

		"tx_typoflash_pageturner" => "Basic settings",
		"tx_typoflash_pageturner.what_to_render" => "Select pages (images or filelist content)",
		"tx_typoflash_pageturner.advanced_settings" => "Advanced settings",
		"tx_typoflash_pageturner.pages" => "Select content element (image or filelist content)",
		"tx_typoflash_pageturner.bgImage" => "Select bg image (image content)",
		
		"tx_typoflash_pageturner.top" => "Distance from top (px)",
		"tx_typoflash_pageturner.left" => "Distance from left (px)",
		"tx_typoflash_pageturner.width" => "Flash width",
		"tx_typoflash_pageturner.height" => "Flash height",
		"tx_typoflash_pageturner.book_width" => "Book width",
		"tx_typoflash_pageturner.book_height" => "Book height",
		"tx_typoflash_pageturner.scaleContent" => "Scale images that don't fit",
		"tx_typoflash_pageturner.firstPage" => "Start on page number",
		"tx_typoflash_pageturner.alwaysOpened" => "Always opened",
		"tx_typoflash_pageturner.autoFlip" => "Autoflip area size",
		"tx_typoflash_pageturner.flipOnClick" => "Flip-on-click",
		"tx_typoflash_pageturner.staticShadowsDepth" => "Static shadow depth",
		"tx_typoflash_pageturner.dynamicShadowsDepth" => "Dynamic shadow depth",
		"tx_typoflash_pageturner.moveSpeed" => "Move speed",
		"tx_typoflash_pageturner.closeSpeed" => "Close speed",
		"tx_typoflash_pageturner.gotoSpeed" => "Goto speed",
		"tx_typoflash_pageturner.flipSound" => "Flip sound",
		"tx_typoflash_pageturner.flipSound.I.0" => "None",
		"tx_typoflash_pageturner.flipSound.I.1" => "Flick sound 1",
		"tx_typoflash_pageturner.flipSound.I.2" => "Flick sound 2",
		"tx_typoflash_pageturner.pageBack" => "Page bg colour",
		"tx_typoflash_pageturner.loadOnDemand" => "Load on demand",
		"tx_typoflash_pageturner.cachePages" => "Cache pages",
		"tx_typoflash_pageturner.cacheSize" => "Cache size",
		"tx_typoflash_pageturner.preloaderType" => "Preloader type",
		"tx_typoflash_pageturner.usePreloader" => "Use preloader",
		"tx_typoflash_pageturner.preloaderType.I.0" => "None",
		"tx_typoflash_pageturner.preloaderType.I.1" => "Round",
		"tx_typoflash_pageturner.preloaderType.I.2" => "Bar",
		"tx_typoflash_pageturner.cachePages" => "Cache pages",
		"tx_typoflash_pageturner.bgColour" => "Background colour",
		"tx_typoflash_pageturner.flash_version" => "Flash version",



		"tx_typoflash_pageturner.textpage_settings" => "Textpage settings",
		"tx_typoflash_pageturner.fontSize" => "Font size",
		"tx_typoflash_pageturner.textBgColour" => "Textfield bg colour. Leave blank for transparent",

		"tx_typoflash_pageturner.textColour" => "Text colour",
		"tx_typoflash_pageturner.textBorderColour" => "Text border colour",
		"tx_typoflash_pageturner.paperWhiteness" => "Paper whiteness (1 oldish - 10 white)",
		"tx_typoflash_pageturner.font" => "Font for textpages",
		"tx_typoflash_pageturner.font.I.0" => "Helvetica",
		"tx_typoflash_pageturner.font.I.1" => "Verdana",
		"tx_typoflash_pageturner.font.I.2" => "Calligraphy",
		"tx_typoflash_pageturner.font.I.3" => "Handwriting",
		"tx_typoflash_pageturner.font.I.4" => "Typewriter",


		"tx_typoflash_pageturner.textWidth" => "Text width",
		"tx_typoflash_pageturner.textHeight" => "Text height",
		"tx_typoflash_pageturner.textTop" => "Text topmargin",
		"tx_typoflash_pageturner.textLeft" => "Text leftmargin",

		"tx_typoflash_mp3.media" => "Media",
		"tx_typoflash_mp3.media_category" => "Category (eg. Media Category or News Category)",
		
		"tx_typoflash_mp3.autostart" => "Autostart",
		"tx_typoflash_mp3.shuffle" => "Shuffle",
		"tx_typoflash_mp3.backcolor" => "Bg colour",
		"tx_typoflash_mp3.frontcolor" => "Fg colour",
		"tx_typoflash_mp3.lightcolor" => "Highlight colour",
		"tx_typoflash_mp3.showeq" => "Show EQ",
		"tx_typoflash_mp3.showdigits" => "Show digits",
		"tx_typoflash_mp3.volume" => "Volume",
		"tx_typoflash_mp3.autoscroll" => "Show scrollbar / Autoscroll",
		"tx_typoflash_mp3.showicons" => "Show icons",
		"tx_typoflash_mp3.linkfromdisplay" => "Link from display",
		"tx_typoflash_mp3.linktarget" => "Link target (a href target)",
		"tx_typoflash_mp3.showfsbutton" => "Show fullscreen button",
		"tx_typoflash_mp3.fullscreenmode" => "Fullscreen mode",
		"tx_typoflash_mp3.fullscreenpage" => "Fullscreen page",
		"tx_typoflash_mp3.fsreturnpage" => "Fullscreen return page",
		"tx_typoflash_mp3.windowmode" => "Window mode",
		"tx_typoflash_mp3.thumbsinplaylist" => "Thumbs in playlist",
		"tx_typoflash_mp3.rotatetime" => "Rotate time",
		"tx_typoflash_mp3.shownavigation" => "shownavigation",
		"tx_typoflash_mp3.enablejs" => "enablejs",
		"tx_typoflash_mp3.callback" => "callback",
		"tx_typoflash_mp3.streamscript" => "streamscript",
		"tx_typoflash_mp3.displayheight" => "Display height",
		"tx_typoflash_mp3.repeat" => "Repeat",


		"tt_content.list_type_pi1" => "TypoFlash: Inline component",
		"tt_content.list_type_pi2" => "TypoFlash: Page turner",
		"tt_content.list_type_pi3" => "TypoFlash: Image viewer",
		"tt_content.list_type_pi4" => "TypoFlash: MP3 player",
		"tt_content.list_type_pi5" => "TypoFlash: Video player",
		"tt_content.list_type_pi6" => "TypoFlash: Media gallery",
		"tx_typoflash_content" => "Flash page content",    
        "tx_typoflash_content.name" => "Name",    
        "tx_typoflash_content.language" => "Language",    
        "tx_typoflash_content.component" => "Component",    
        "tx_typoflash_content.records" => "Records",    
        "tx_typoflash_content.storage_page" => "Storage page",    
        "tx_typoflash_content.media" => "Media", 
		"tx_typoflash_content.media_category" => "Category (eg. Media Category or News Category)", 
        "tx_typoflash_content.conf" => "Configuration",    
        "tx_typoflash_content.xml_conf" => "XML configuration",    
        "tx_typoflash_content.title" => "Title",    
        "tx_typoflash_content.body_text" => "Body text", 
		"tx_typoflash_template.preloader" => "External preloader",  
		"tx_typoflash_template.fonts" => "Shared fonts",  
        "tx_typoflash_template.swfs" => "Files to preload",    
        "tx_typoflash_template.hosturl" => "Host URL (eg. http://elevated.to/)",    
        "tx_typoflash_template.relaysocket" => "Relay socket (eg. elevated.to)",    
        "tx_typoflash_template.relayport" => "Relay port (eg. 8888)",    
        "tx_typoflash_template.relayserver" => "Relay server (eg. elevated.to_8888.php)",    
        "tx_typoflash_template.codepage" => "Use codepage",    
        "tx_typoflash_template.scalemode.I.0" => "noScale",    
        "tx_typoflash_template.scalemode.I.1" => "noborder",    
        "tx_typoflash_template.scalemode.I.2" => "exactfit",    
        "tx_typoflash_template.scalemode" => "Scale mode",    
        "tx_typoflash_template.align.I.0" => "Top left",    
        "tx_typoflash_template.align.I.1" => "Top center",    
        "tx_typoflash_template.align.I.2" => "Top right",    
        "tx_typoflash_template.align.I.3" => "Center left",    
        "tx_typoflash_template.align.I.4" => "Center right",    
        "tx_typoflash_template.align.I.5" => "Bottom left",    
        "tx_typoflash_template.align.I.6" => "Bottom center",    
        "tx_typoflash_template.align.I.7" => "Bottom right",    
        "tx_typoflash_template.align" => "Align",    
        "tx_typoflash_template.windowmode.I.0" => "window",    
        "tx_typoflash_template.windowmode.I.1" => "opaque",    
        "tx_typoflash_template.windowmode.I.2" => "transparent",    
        "tx_typoflash_template.windowmode" => "Window mode",
	),
	"fr" => Array (
	),
	"es" => Array (
	),
	"se" => Array (
	),
);
?>